/**
 * Build-time prerender script.
 * Run after: npm run build && npm run extract-routes && vite build --ssr src/entry-server.tsx --outDir dist/server
 *
 * Reads dist/index.html, renders each route via entry-server, injects HTML + head tags,
 * writes to dist/{path}/index.html. Also generates sitemap.xml, robots.txt, and 404.html.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DIST = join(ROOT, 'dist');
const SITE_URL = 'https://tripointdiagnostics.co.uk';

// Load route manifest (generated by extract-routes.mjs)
const routesJsonPath = join(ROOT, 'src', 'routes.manifest.json');
const routeManifest = JSON.parse(readFileSync(routesJsonPath, 'utf8'));

async function runPrerender() {
    const template = readFileSync(join(DIST, 'index.html'), 'utf8');

    // Load the server render function (use pathToFileURL for Windows compatibility)
    const entryServerPath = pathToFileURL(join(DIST, 'server', 'entry-server.js')).href;
    const { render } = await import(entryServerPath);

    const indexableRoutes = routeManifest.filter((r) => r.indexable);

    for (const route of indexableRoutes) {
        const { appHtml, helmet } = render(route.path);
        const headTags = helmet
            ? [
                  helmet.title?.toString?.() ?? '',
                  helmet.meta?.toString?.() ?? '',
                  helmet.link?.toString?.() ?? '',
              ]
                  .filter(Boolean)
                  .join('\n')
            : '';

        let html = template
            .replace('<!--head-tags-->', headTags)
            .replace('<!--app-html-->', appHtml);

        const outPath = route.path === '/' ? join(DIST, 'index.html') : join(DIST, route.path, 'index.html');
        mkdirSync(dirname(outPath), { recursive: true });
        writeFileSync(outPath, html, 'utf8');
        console.log('Prerendered:', route.path);
    }

    // 404 page
    const notFound = render('/404');
    const headTags404 = notFound.helmet
        ? [
              notFound.helmet.title?.toString?.() ?? '',
              notFound.helmet.meta?.toString?.() ?? '',
              notFound.helmet.link?.toString?.() ?? '',
          ]
              .filter(Boolean)
              .join('\n')
        : '';
    let html404 = template
        .replace('<!--head-tags-->', headTags404)
        .replace('<!--app-html-->', notFound.appHtml);
    writeFileSync(join(DIST, '404.html'), html404, 'utf8');
    console.log('Prerendered: 404.html');

    // Sitemap
    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexableRoutes
    .map(
        (r) => `  <url>
    <loc>${SITE_URL}${r.canonicalPath || r.path}</loc>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`
    )
    .join('\n')}
</urlset>`;
    writeFileSync(join(DIST, 'sitemap.xml'), sitemap, 'utf8');
    console.log('Generated: sitemap.xml');

    // robots.txt
    const robots = `User-agent: *
Allow: /
Disallow: /admin
Disallow: /admin/
Disallow: /pay

Sitemap: ${SITE_URL}/sitemap.xml
`;
    writeFileSync(join(DIST, 'robots.txt'), robots, 'utf8');
    console.log('Generated: robots.txt');
}

runPrerender().catch((err) => {
    console.error('Prerender failed:', err);
    process.exit(1);
});
